version: '3.3'
services:
  app:
    container_name: heimdallr-service
    image: titipaja/heimdallr-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'vol-heimdallr-gw:/app/heimdallr/'
    ports:
      - 9000:9000
    network_mode: titipaja-net
volumes:
  vol-heimdallr-gw:
    external: true
