version: '3.3'
services:
  app:
    container_name: heimdallr-service
    image: titipaja/heimdallr-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './be:/heimdallr/'
    ports:
      - 9080:9080
    network_mode: titipaja-net
volumes:
  data:
    external: true
